- hosts: all

  become: true
  become_method: sudo
  
  tasks:
    - name: install pip docker
      ansible.builtin.pip:
        name: docker

    - name: add network
      community.docker.docker_network:
        name: my_network
    
    - name: create docker nginx
      community.docker.docker_container:
        name: nginx-proxy
        image: nginx
        restart_policy: always
        state: started
        ports:
          - 80:80
          - 443:443
        volumes:
#           - /project/code/nginx.conf:/etc/nginx/conf.d/default.conf
          - /project/code/:/etc/nginx/conf.d/
          - /srv/docker/redmine/redmine/certs:/etc/nginx/certs
        networks:
          - name: my_network

    - name: create docker redmine 
      community.docker.docker_container:
        name: redmine
        image: redmine
        restart_policy: always
        state: started
        ports:
          - 3000:3000
        env:
          NODE_ENV: production
          REDMINE_HTTPS: "true"
          REDMINE_DB_POSTGRES: "{{ REDMINE_DB_POSTGRES }}"
          REDMINE_DB_PORT: "{{ REDMINE_DB_PORT }}"
          REDMINE_DB_DATABASE: "{{ REDMINE_DB_DATABASE }}"
          REDMINE_DB_USERNAME: "{{ REDMINE_DB_USERNAME }}"
          REDMINE_DB_PASSWORD: "{{ REDMINE_DB_PASSWORD }}"
        networks:
          - name: my_network
- hosts: webservers
  become: true
  name: Run datadog agent
  roles: 
    - role: datadog.datadog
